In [1]:
!pip install ydata_profiling matplotlib

Collecting ydata_profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (2.2.2)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (2.0.2)
Collecting htmlmin==0.1.12 (from ydata_profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata_profiling)
  Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata_profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (4.4.3)
Collecting imagehash==4.3.1 (from ydata_profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (1.9.4)
Collecting dacite>=1.8 (from ydata_profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from ydata_profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata_profiling) (1.8.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata_profiling) (11.2.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata_profiling) (3.0.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba<=0.61,>=0.56.0->ydata_profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata_profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata_profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata_profiling) (1.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata_profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata_profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata_profiling) (4.14.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata_profiling) (0.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (2025.6.15)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.5)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading puremagic-1.29-py3-none-any.whl.metadata (5.8 kB)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 18.5 MB/s eta 0:00:00
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 22.1 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (687 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 39.4 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.0 MB/s eta 0:00:00
Downloading puremagic-1.29-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 1.9 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=7ecac81b2b350d347b5d5b726f010ae8fa622cafae0c2ea295a2173e6bf7ff8c
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, multimethod, dacite, imagehash, visions, phik, ydata_profiling
Successfully installed dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.4 puremagic-1.29 visions-0.8.1 ydata_profiling-4.16.1

In [2]:
import pandas as pd
from ydata_profiling import ProfileReport

In [3]:
dados = pd.read_csv("https://raw.githubusercontent.com/MachineTeachingEdu/JAI2025-IA-Educacao/refs/heads/main/An%C3%A1lise%20de%20Dados/dataset.txt", sep='\t')

In [4]:
def limpeza_inicial(dados):
  # prompt: drop all df columns that are all NaN
  dados.dropna(axis=1, how='all', inplace=True)

  # prompt: drop all df columns that have a single unique value
  columns_to_drop = []
  for col in dados.columns:
      if dados[col].nunique() == 1:
          columns_to_drop.append(col)
  dados.drop(columns=columns_to_drop, inplace=True)

  dados.drop(["Row", "Transaction Id", "Tutor Response Type"], axis=1, inplace=True)

  # prompt: transform a datetime column called "Problem Start Time" in a pandas df into seconds from 1970
  dados["Problem Start Time"] = pd.to_datetime(dados["Problem Start Time"]).astype('int64') // 10**9
  return dados

dados = limpeza_inicial(dados)

In [5]:
profile = ProfileReport(dados,title="Computação")
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/19 [00:00<?, ?it/s]
  5%|▌         | 1/19 [00:00<00:03,  5.14it/s]
 16%|█▌        | 3/19 [00:00<00:01,  8.31it/s]
 26%|██▋       | 5/19 [00:00<00:01,  9.38it/s]
 42%|████▏     | 8/19 [00:00<00:00, 12.14it/s]
 58%|█████▊    | 11/19 [00:00<00:00, 15.35it/s]
 68%|██████▊   | 13/19 [00:01<00:00,  9.26it/s]
 79%|███████▉  | 15/19 [00:01<00:00,  9.58it/s]
 89%|████████▉ | 17/19 [00:01<00:00,  8.94it/s]
100%|██████████| 19/19 [00:01<00:00, 10.22it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
habilidade_aluno = dados[['KC (Intro CS Concepts)', "Anon Student Id"]]
habilidade_aluno = habilidade_aluno.drop_duplicates()
print("Quantidade de habilidades no dataset: ", len(habilidade_aluno['KC (Intro CS Concepts)'].unique()))
habilidades = habilidade_aluno['KC (Intro CS Concepts)'].unique()
habilidade_aluno['KC (Intro CS Concepts)'].value_counts()

Quantidade de habilidades no dataset:  10

KC (Intro CS Concepts)
Class and Functions                  89
Data Types and Structures            87
Variables                            78
Programming Language Fundamentals    78
Arithmetic Operations                76
Comparison                           50
Boolean Operation                    32
Boolean Operations                   32
Loops                                32
Conditions                           27
Name: count, dtype: int64

In [7]:
def transforma_dataset(aluno_id, habilidades):
  aluno = dados[(dados['Anon Student Id'] == aluno_id) & (dados['Is Last Attempt'] == 1)]
  habilidade_aluno = aluno['KC (Intro CS Concepts)'].unique()
  dataset_aluno = {"Id": aluno_id}
  # print(f"{aluno_id}")
  for habilidade in habilidade_aluno:
    tem_habilidade = aluno[aluno['KC (Intro CS Concepts)'] == habilidade]
    if len(tem_habilidade) > 0:
      sucesso = tem_habilidade[tem_habilidade['Outcome'] == 'CORRECT'].count()['Outcome']
      total = tem_habilidade.count()['Outcome']
      # print(f"{sucesso} / {total} = {sucesso/total}")
      dataset_aluno[habilidade] = sucesso/total
    else:
      dataset_aluno[habilidade] = 0.1
  return pd.DataFrame.from_dict([dataset_aluno], orient='columns')

dados_final = pd.DataFrame()
for aluno_id in dados['Anon Student Id'].unique():
  dados_aluno = transforma_dataset(aluno_id, habilidades)
  dados_final = pd.concat([dados_final, dados_aluno])
dados_final = dados_final.fillna(0)

In [8]:
dados_final.head()

,Id,Data Types and Structures,Arithmetic Operations,Programming Language Fundamentals,Class and Functions,Variables,Comparison,Boolean Operation,Boolean Operations,Loops,Conditions
0,S002,0.833333,0.857143,0.800000,0.888889,0.857143,0.666667,1.0,1.00,0.0,0.0
0,S011,0.846154,0.765957,0.903226,0.902439,0.758621,0.812500,1.0,0.75,0.5,1.0
0,S014,0.923077,0.750000,0.937500,0.961538,0.923077,1.000000,0.0,0.00,0.0,0.0
0,S020,0.833333,0.833333,0.800000,0.967742,0.789474,0.666667,0.0,0.00,0.0,0.0
0,S023,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.0,0.50,0.0,0.0

In [9]:
dados_final.to_csv('dados_final_habilidades.csv', index=False)

In [10]:
profile = ProfileReport(dados_final,title="Dataset Transformado")
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/11 [00:00<?, ?it/s]
100%|██████████| 11/11 [00:00<00:00, 106.61it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]